version: '2.2'

services:
    prometheus:
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    blackbox:
        image: bitnami/blackbox-exporter
        ports:
          - "9115:9115"
        volumes:
          - ./blackbox-exporter/blackbox.yml:/opt/bitnami/blackbox-exporter/blackbox.yml

    grafana:
        image: grafana/grafana
        ports:
          - "3000:3000"
        volumes:
          - grafana:/var/lib/grafana
          - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
          - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
          - ./grafana/dashboards/:/var/lib/grafana/dashboards/
        environment:
          GF_SECURITY_ADMIN_PASSWORD: pass
        depends_on:
          - prometheus
        logging:
            driver: none

volumes:
    grafana:
      driver: local