version: '2.2'

services:
    nginx:
        image: nginx
        ports:
          - "80:80"
        volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf:ro

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter:0.2.0
        ports:
          - "9113:9113"
        command: -nginx.scrape-uri http://nginx/stub_status
        depends_on:
          - nginx

    prometheus:
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        ports:
          - "3000:3000"
        volumes:
          - grafana:/var/lib/grafana
        depends_on:
          - prometheus

volumes:
    grafana:
      driver: local